"""
Kalshi Arbitrage Bot
=====================

A sophisticated arbitrage detection and execution system for Kalshi prediction markets.

Based on the mathematical frameworks from:
- "Unravelling the Probabilistic Forest: Arbitrage in Prediction Markets" (arXiv:2508.03474v1)
- "Arbitrage-Free Combinatorial Market Making via Integer Programming" (arXiv:1606.02825v2)

Key Components:
- Integer Programming for dependency detection
- Frank-Wolfe algorithm with Bregman projection
- Barrier Frank-Wolfe with adaptive contraction
- Real-time execution engine

Author: Generated by OpenCode
"""

__version__ = "0.1.0"
__author__ = "Kalshi Arbitrage Bot"
